#Demostracion que esta cargado VSC - Pyhton - GitBash en mi maquina personal
print("***********************************")
print("* Hola Mundo... Soy Monica Antich *")
print("***********************************")
a = float(input("Ingrese un numero: "))
b = float(input("Ingrese otro numero: "))
suma=(a+b)
resta=(a-b)
producto=(a*b)
division=(a/b)
print("El resultado de la suma es:", suma)
print("El resultado de la resta es:", resta)
print("El resultado del producto es:", producto)
print("El resultado de la division es:", division)
print("***********************************")
print("* Chau Mundo... Soy Monica Antich *")
print("***********************************")
